name: Back-End CI/CD

on: 
  push:
  pull_request:

jobs:
  # Building pipeline
  build: 
    name: Build Spring Boot App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Generate real private key
        run: |
          mkdir -p orelease-etc-backend/src/main/resources/sec
          sudo openssl genpkey -algorithm RSA -out orelease-etc-backend/src/main/resources/sec/pr_key.pem -pkeyopt rsa_keygen_bits:2048

      - name: Generate real public key
        run: |
          sudo openssl rsa -pubout -in orelease-etc-backend/src/main/resources/sec/pr_key.pem -out orelease-etc-backend/src/main/resources/sec/pu_key.pem

      - name: Debug key file presence
        run: ls -al orelease-etc-backend/src/main/resources/sec/
      
      - name: Validate decoded keys
        run: |
          echo "Private key:"
          cat orelease-etc-backend/src/main/resources/sec/pr_key.pem | head -n 2
          echo "Public key:"
          cat orelease-etc-backend/src/main/resources/sec/pu_key.pem | head -n 2
      
      - name: Install open-java 17
        run: |
          sudo apt install -y openjdk-17-jdk

      - name: Check Java Version
        run: java -version

      - name: Install mvn
        run: sudo apt-get install -y maven

      - name: Build using Maven
        run: mvn -f orelease-etc-backend/pom.xml clean install

  # Testing pipeline
  test:
    name: Test Spring Boot App
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Generate real private key
        run: |
          mkdir -p orelease-etc-backend/src/main/resources/sec
          sudo openssl genpkey -algorithm RSA -out orelease-etc-backend/src/main/resources/sec/pr_key.pem -pkeyopt rsa_keygen_bits:2048

      - name: Generate real public key
        run: |
          sudo openssl rsa -pubout -in orelease-etc-backend/src/main/resources/sec/pr_key.pem -out orelease-etc-backend/src/main/resources/sec/pu_key.pem

      - name: Debug key file presence
        run: ls -al orelease-etc-backend/src/main/resources/sec/

      - name: Validate decoded keys
        run: |
          echo "Private key:"
          cat orelease-etc-backend/src/main/resources/sec/pr_key.pem | head -n 2
          echo "Public key:"
          cat orelease-etc-backend/src/main/resources/sec/pu_key.pem | head -n 2

      - name: Install Java and Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk maven
          java -version
          mvn -version

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests using Maven
        run: mvn -f orelease-etc-backend/pom.xml test

  # Deployment pipeline
  deploy:
    name: Deploying 
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Deploying
        run: echo "Deploying Spring Boot Application"

  # Cleanup pipeline
  cleanup:
    name: Clean-up 
    runs-on: ubuntu-latest
    needs: deploy
    if: always() # run even other jobs fail
    steps:
      - name: Removing temp directory and target
        run: |
          rm -rf ~/.m2/repository/temp
          rm -rf target

      - name: Remove generated keys
        run: |
          rm -rf orelease-etc-backend/src/main/resources/sec/pr_key.pem
          rm -rf orelease-etc-backend/src/main/resources/sec/pu_key.pem
