name: Front-End CI/CD 

on: 
  push: 
  pull_request:

env:
  DIR: ./orelease-etc-frontend/er-to-code/

jobs:
  # Building pipeline
  frontend: 
    name: Build and Test
    runs-on: ubuntu-latest
 
    steps: 
      # chechout the repo: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-versions: 18
          
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.DIR }}


      - name: run tests
        run: npm test
        working-directory: ${{ env.DIR }}


  cleanup:
    name: Clean files
    runs-on: ubuntu-latest
    needs: frontend
    
    steps: 
      - name: clean cache
        run: npm cache clean --force 

      - name: Remove modules
        run: rm -rf node_modules
        working-directory: ${{ env.DIR }}

      - name: rmeove build dir
        run: rm -rf build
        working-directory: ${{ env.DIR }}

      - name: confirm clean
        run: |
          dirs=$(ls -al | grep build)
          dir+=$(ls -al | grep node_modules)
          if [ "${#dirs[@]}" -ne 0 ]; then exit 1 fi 
        working-directory: ${{ env.DIR }}

